"""Rust-vs-Python golden comparison tests.

These tests verify that the Python implementations produce numerically
identical results to the Rust implementations using the same external
dependencies (nalgebra, ahrs) as Gyroflow.

The Rust golden data is generated by:
    cargo run --release -p msgyro-golden-gen -- tests/golden/imu_data.json tests/golden/

Tolerance: 1e-6 for quaternion components (covers floating-point differences
between Python's scipy.spatial.transform.Rotation and Rust's nalgebra).
"""

import json
import math
from pathlib import Path

import numpy as np
import pytest

GOLDEN_DIR = Path(__file__).parent / "golden"


def load_rust_golden(integrator_name: str) -> dict:
    path = GOLDEN_DIR / f"rust_imu_{integrator_name}.json"
    if not path.exists():
        pytest.skip(f"Rust golden data not found: {path}")
    with open(path) as f:
        return json.load(f)


def load_python_golden(integrator_name: str) -> dict:
    path = GOLDEN_DIR / f"imu_{integrator_name}.json"
    if not path.exists():
        pytest.skip(f"Python golden data not found: {path}")
    with open(path) as f:
        return json.load(f)


def assert_quats_match(
    rust_quats: dict[str, list],
    python_quats: dict[str, list],
    tol: float = 1e-6,
):
    """Compare Rust and Python quaternion outputs, handling double-cover.

    Timestamps may differ by ±1 due to float→int truncation differences.
    We match each Rust timestamp to the closest Python timestamp within 2μs.
    """
    rust_ts = sorted(int(k) for k in rust_quats.keys())
    py_ts = sorted(int(k) for k in python_quats.keys())

    max_error = 0.0
    max_error_ts = ""
    error_count = 0
    matched = 0

    for ts in rust_ts:
        # Find closest Python timestamp within 2μs
        closest = min(py_ts, key=lambda t: abs(t - ts))
        if abs(closest - ts) > 2:
            continue

        rq = np.array(rust_quats[str(ts)])
        pq = np.array(python_quats[str(closest)])

        # Handle double-cover: q and -q are equivalent
        if np.dot(rq, pq) < 0:
            pq = -pq

        diff = np.abs(rq - pq)
        err = np.max(diff)
        matched += 1
        if err > max_error:
            max_error = err
            max_error_ts = str(ts)
        if err > tol:
            error_count += 1

    assert matched > 0, "No timestamps could be matched between Rust and Python"
    assert max_error <= tol, (
        f"Quaternion mismatch: max_error={max_error:.2e} at ts={max_error_ts}us, "
        f"{error_count}/{matched} samples exceed tol={tol}. "
        f"Rust={rust_quats[max_error_ts]}, Python={python_quats[max_error_ts]}"
    )


class TestRustPythonIMUIntegration:
    """Compare Python IMU integration against Rust golden data.

    Each test loads the Rust reference output and re-runs the Python
    integrator on the same input data, comparing results.
    """

    @pytest.fixture(scope="class")
    def imu_data(self):
        path = GOLDEN_DIR / "imu_data.json"
        if not path.exists():
            pytest.skip("IMU data file not found")
        with open(path) as f:
            return json.load(f)

    @pytest.fixture(scope="class")
    def imu_list(self, imu_data):
        from pygyroflow.types.time_types import TimeIMU
        return [
            TimeIMU(
                timestamp_ms=s["timestamp_ms"],
                gyro=np.array(s["gyro"]) if s["gyro"] else None,
                accl=np.array(s["accl"]) if s["accl"] else None,
                magn=np.array(s["magn"]) if s["magn"] else None,
            )
            for s in imu_data["samples"]
        ]

    @pytest.mark.parametrize("integrator_name", [
        "simple_gyro", "simple_gyro_accel", "mahony", "madgwick",
        "complementary",
        "vqf",
    ])
    def test_imu_integration_matches_rust(self, integrator_name, imu_list, imu_data):
        from pygyroflow.imu_integration import (
            SimpleGyroIntegrator, SimpleGyroAccelIntegrator,
            MahonyIntegrator, MadgwickIntegrator, ComplementaryIntegrator,
            VQFIntegrator,
        )
        integrators = {
            "simple_gyro": SimpleGyroIntegrator,
            "simple_gyro_accel": SimpleGyroAccelIntegrator,
            "mahony": MahonyIntegrator,
            "madgwick": MadgwickIntegrator,
            "complementary": ComplementaryIntegrator,
            "vqf": VQFIntegrator,
        }

        rust_data = load_rust_golden(integrator_name)
        integrator = integrators[integrator_name]()
        result = integrator.integrate(imu_list, imu_data["duration_ms"])

        # Convert Python result to same format as Rust
        py_quats = {}
        for ts, q in result.items():
            py_quats[str(ts)] = q.quaternion().tolist()

        rust_quats = rust_data["quaternions"]

        assert_quats_match(rust_quats, py_quats, tol=1e-6)


class TestRustPythonGoldenSummary:
    """Report a summary of Rust-Python agreement across all integrators."""

    def test_agreement_summary(self, capsys):
        """Print a summary of max errors for each integrator."""
        from pygyroflow.types.time_types import TimeIMU

        imu_path = GOLDEN_DIR / "imu_data.json"
        if not imu_path.exists():
            pytest.skip("IMU data file not found")

        with open(imu_path) as f:
            imu_data = json.load(f)

        imu_list = [
            TimeIMU(
                timestamp_ms=s["timestamp_ms"],
                gyro=np.array(s["gyro"]) if s["gyro"] else None,
                accl=np.array(s["accl"]) if s["accl"] else None,
                magn=np.array(s["magn"]) if s["magn"] else None,
            )
            for s in imu_data["samples"]
        ]

        from pygyroflow.imu_integration import (
            SimpleGyroIntegrator, SimpleGyroAccelIntegrator,
            MahonyIntegrator, MadgwickIntegrator, ComplementaryIntegrator,
            VQFIntegrator,
        )
        integrators = {
            "simple_gyro": SimpleGyroIntegrator,
            "simple_gyro_accel": SimpleGyroAccelIntegrator,
            "mahony": MahonyIntegrator,
            "madgwick": MadgwickIntegrator,
            "complementary": ComplementaryIntegrator,
            # VQF has no Rust golden yet (msgyro-golden-gen doesn't emit it);
            # included here so the coverage gap is visible in the summary.
            "vqf": VQFIntegrator,
        }

        results = []
        for name, cls in integrators.items():
            rust_path = GOLDEN_DIR / f"rust_imu_{name}.json"
            if not rust_path.exists():
                results.append(f"  {name:25s}: SKIP (no Rust golden data)")
                continue

            with open(rust_path) as f:
                rust_data = json.load(f)

            integrator = cls()
            py_result = integrator.integrate(imu_list, imu_data["duration_ms"])

            max_err = 0.0
            mean_err = 0.0
            count = 0
            py_ts_sorted = sorted(py_result.keys())
            for ts_str, rq_list in rust_data["quaternions"].items():
                ts = int(ts_str)
                # Find closest Python timestamp
                closest = min(py_ts_sorted, key=lambda t: abs(t - ts))
                if abs(closest - ts) > 2:
                    continue
                rq = np.array(rq_list)
                pq = py_result[closest].quaternion()
                if np.dot(rq, pq) < 0:
                    pq = -pq
                err = np.max(np.abs(rq - pq))
                max_err = max(max_err, err)
                mean_err += err
                count += 1

            mean_err /= max(count, 1)
            status = "PASS" if max_err < 1e-6 else "FAIL"
            results.append(
                f"  {name:25s}: {status}  max_err={max_err:.2e}  mean_err={mean_err:.2e}  n={count}"
            )

        with capsys.disabled():
            print("\n=== Rust vs Python IMU Integration Comparison ===")
            for r in results:
                print(r)
            print("=" * 55)
