"""Golden comparison tests: verify Python implementation produces consistent results.

These tests load reference data generated by generate_references.py and re-run
the same algorithms, checking that results match within numerical tolerance.
This catches regressions and ensures the Python port stays consistent.

For true Rust-vs-Python comparison, the Rust workspace should generate equivalent
golden data and the paths should be swapped here.
"""

import json
import math
from pathlib import Path

import numpy as np
import pytest

GOLDEN_DIR = Path(__file__).parent / "golden"


def assert_quats_close(actual, expected, tol=1e-6):
    """Compare two TimeQuat maps, handling quaternion double-cover."""
    assert set(actual.keys()) == set(expected.keys()), \
        f"Timestamp mismatch: extra={set(actual.keys()) - set(expected.keys())}, missing={set(expected.keys()) - set(actual.keys())}"
    for ts in actual:
        q1 = actual[ts].quaternion()
        q2 = expected[ts].quaternion()
        if np.dot(q1, q2) < 0:
            q2 = -q2
        np.testing.assert_allclose(q1, q2, atol=tol, err_msg=f"Quaternion mismatch at t={ts}")


def load_golden(name: str) -> dict:
    path = GOLDEN_DIR / f"{name}.json"
    if not path.exists():
        pytest.skip(f"Golden data file not found: {path}")
    with open(path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# IMU integration golden tests
# ---------------------------------------------------------------------------

class TestGoldenIMUIntegration:
    """Re-run each IMU integrator on the golden input data and compare."""

    @pytest.fixture(scope="class")
    def imu_data(self):
        return load_golden("imu_data")

    @pytest.fixture(scope="class")
    def imu_list(self, imu_data):
        from pygyroflow.types.time_types import TimeIMU
        return [
            TimeIMU(
                timestamp_ms=s["timestamp_ms"],
                gyro=np.array(s["gyro"]) if s["gyro"] else None,
                accl=np.array(s["accl"]) if s["accl"] else None,
                magn=np.array(s["magn"]) if s["magn"] else None,
            )
            for s in imu_data["samples"]
        ]

    @pytest.mark.parametrize("integrator_name", [
        "simple_gyro", "simple_gyro_accel", "mahony", "madgwick", "complementary",
    ])
    def test_imu_integration_matches_golden(self, integrator_name, imu_list, imu_data):
        from pygyroflow.imu_integration import (
            SimpleGyroIntegrator, SimpleGyroAccelIntegrator,
            MahonyIntegrator, MadgwickIntegrator, ComplementaryIntegrator,
        )
        integrators = {
            "simple_gyro": SimpleGyroIntegrator,
            "simple_gyro_accel": SimpleGyroAccelIntegrator,
            "mahony": MahonyIntegrator,
            "madgwick": MadgwickIntegrator,
            "complementary": ComplementaryIntegrator,
        }
        golden = load_golden(f"imu_{integrator_name}")
        integrator = integrators[integrator_name]()
        result = integrator.integrate(imu_list, imu_data["duration_ms"])

        golden_quats = {}
        for ts_str, q_list in golden["quaternions"].items():
            from pygyroflow.types.quaternion import Quat64
            golden_quats[int(ts_str)] = Quat64.from_quaternion(q_list)

        assert_quats_close(result, golden_quats, tol=1e-10)


# ---------------------------------------------------------------------------
# Smoothing golden tests
# ---------------------------------------------------------------------------

class TestGoldenSmoothing:
    """Re-run smoothing algorithms on golden input and compare."""

    def _load_quats(self, quats_dict):
        from pygyroflow.types.quaternion import Quat64
        result = {}
        for ts_str, q_list in quats_dict.items():
            result[int(ts_str)] = Quat64.from_quaternion(q_list)
        return result

    @pytest.mark.parametrize("algo_name,params", [
        ("default_0.3", {"smoothness": 0.3}),
        ("default_0.7", {"smoothness": 0.7}),
        ("plain", {"time_constant": 0.3}),
    ])
    def test_smoothing_matches_golden(self, algo_name, params):
        from pygyroflow.smoothing import DefaultAlgo, PlainSmoothing
        from pygyroflow.stabilization import ComputeParams

        golden = load_golden(f"smoothing_{algo_name}")
        input_quats = self._load_quats(golden["input_quaternions"])

        algo_cls = DefaultAlgo if algo_name.startswith("default") else PlainSmoothing
        algo = algo_cls()
        for k, v in params.items():
            algo.set_parameter(k, v)

        n = len(input_quats)
        duration_ms = golden["duration_ms"]
        cp = ComputeParams(
            width=1920, height=1080, output_width=1920, output_height=1080,
            frame_count=n, scaled_fps=n / (duration_ms / 1000.0),
            scaled_duration_ms=duration_ms,
            quaternions=input_quats, fovs=[1.0] * n, fov_scale=1.0,
        )

        result = algo.smooth(input_quats, duration_ms, cp)
        expected = self._load_quats(golden["output_quaternions"])
        assert_quats_close(result, expected, tol=1e-10)


# ---------------------------------------------------------------------------
# Distortion model golden tests
# ---------------------------------------------------------------------------

class TestGoldenDistortion:
    """Re-run distortion/undistortion on golden test points and compare."""

    @pytest.mark.parametrize("model_name", [
        "opencv_fisheye", "opencv_standard", "poly3", "poly5", "ptlens",
    ])
    def test_distortion_matches_golden(self, model_name):
        from pygyroflow.stabilization.distortion_models import from_name
        from pygyroflow.types.kernel_params import kernel_params_from_dict

        golden = load_golden(f"distortion_{model_name}")
        model = from_name(model_name)

        coeffs = golden["coefficients"]
        kp = kernel_params_from_dict({
            "k1": coeffs["k1"],
            "k2": coeffs["k2"],
            "k3": coeffs["k3"],
        })

        for tp in golden["test_points"]:
            x, y, z = tp["input_3d"]
            dx, dy = model.distort_point(x, y, z, kp)

            np.testing.assert_allclose([dx, dy], tp["distorted"], atol=1e-8,
                                       err_msg=f"distort_point mismatch for {model_name} at ({x},{y},{z})")

            ux, uy = model.undistort_point(dx, dy, kp)
            np.testing.assert_allclose([ux, uy], tp["undistorted"], atol=1e-8,
                                       err_msg=f"undistort_point mismatch for {model_name} at ({dx},{dy})")

            roundtrip_err = math.sqrt((x - ux) ** 2 + (y - uy) ** 2)
            np.testing.assert_allclose(roundtrip_err, tp["roundtrip_error"], atol=1e-8)


# ---------------------------------------------------------------------------
# Frame transform golden tests
# ---------------------------------------------------------------------------

class TestGoldenFrameTransform:
    """Re-run frame transform computation on golden inputs and compare."""

    def test_frame_transform_matches_golden(self):
        from pygyroflow.types.quaternion import Quat64
        from pygyroflow.stabilization import ComputeParams, FrameTransform

        golden = load_golden("frame_transform")

        quats = {}
        smoothed = {}
        for t_info in golden["transforms"]:
            t_us = int(t_info["timestamp_ms"] * 1000)
            quats[t_us] = Quat64.from_euler_angles(0.0, 0.0, t_info["frame"] * 0.005)
            smoothed[t_us] = Quat64.from_euler_angles(0.0, 0.0, t_info["frame"] * 0.005 * 0.5)

        cp = ComputeParams(
            width=1920, height=1080, output_width=1920, output_height=1080,
            frame_count=60, scaled_fps=60.0, scaled_duration_ms=1000.0,
            quaternions=quats, smoothed_quaternions=smoothed,
            fovs=[1.0] * 60, fov_scale=1.0,
            camera_matrix=np.array([
                [1000.0, 0.0, 960.0],
                [0.0, 1000.0, 540.0],
                [0.0, 0.0, 1.0],
            ]),
            distortion_coeffs=[0.0] * 12,
            frame_readout_time=0.0,
        )

        for t_info in golden["transforms"]:
            frame_idx = t_info["frame"]
            timestamp_ms = t_info["timestamp_ms"]
            ft = FrameTransform.at_timestamp(cp, timestamp_ms, frame_idx)

            assert ft.matrices.shape[0] == t_info["matrix_count"], \
                f"Matrix count mismatch at frame {frame_idx}"
            if t_info["matrices_0"]:
                np.testing.assert_allclose(
                    ft.matrices[0].tolist(), t_info["matrices_0"],
                    atol=1e-5, err_msg=f"Matrix mismatch at frame {frame_idx}",
                )
            np.testing.assert_allclose(
                ft.fov, t_info["fov"], atol=1e-6,
                err_msg=f"FOV mismatch at frame {frame_idx}",
            )


# ---------------------------------------------------------------------------
# VQF golden test (uses same synthetic IMU data)
# ---------------------------------------------------------------------------

class TestGoldenVQF:
    """VQF integration golden test — verifies deterministic output."""

    def test_vqf_deterministic(self):
        from pygyroflow.imu_integration.vqf import VQFIntegrator
        from pygyroflow.types.time_types import TimeIMU

        imu_data = load_golden("imu_data")
        imu_list = [
            TimeIMU(
                timestamp_ms=s["timestamp_ms"],
                gyro=np.array(s["gyro"]) if s["gyro"] else None,
                accl=np.array(s["accl"]) if s["accl"] else None,
                magn=np.array(s["magn"]) if s["magn"] else None,
            )
            for s in imu_data["samples"]
        ]

        integrator = VQFIntegrator()
        result = integrator.integrate(imu_list, imu_data["duration_ms"])

        # Run again — must produce identical results
        result2 = integrator.integrate(imu_list, imu_data["duration_ms"])
        assert_quats_close(result, result2, tol=1e-15)

        # Verify output covers the expected time range
        assert len(result) > 0
        ts_sorted = sorted(result.keys())
        assert ts_sorted[0] == 0
        assert ts_sorted[-1] >= int(imu_data["duration_ms"] * 1000) - 10000
