"""Regenerate tests/golden/gopro6_superview.json.

The expected values are upstream Rust output, not the Python port's — see
``gopro6_superview_reference.rs`` (a byte-for-byte copy of
``opensource/gyroflow/src/core/stabilization/distortion_models/gopro6_superview.rs``)
and ``gopro6_superview_reference_main.rs`` (the driver, which also carries the
two stub modules the copied file imports). To reproduce:

    mkdir -p /tmp/gp6ref/src
    cp tests/golden/gopro6_superview_reference.Cargo.toml /tmp/gp6ref/Cargo.toml
    cp tests/golden/gopro6_superview_reference.rs       /tmp/gp6ref/src/gopro6_superview.rs
    cp tests/golden/gopro6_superview_reference_main.rs  /tmp/gp6ref/src/main.rs
    cd /tmp/gp6ref && cargo build --release --offline
    python tests/golden/generate_gopro6_superview_reference.py /tmp/gp6ref

``--check`` runs the binary against the committed fixture and reports
differences instead of rewriting it:

    python tests/golden/generate_gopro6_superview_reference.py --check /tmp/gp6ref

The probe list lives here rather than in the fixture so the whole file is
reproducible from source; only the two output arrays come from the Rust.

Two of the probes are deliberate. ``(100, 900)`` sits where the fixed-point
inversion needs 22 steps to reach the 1e-6 epsilon while upstream's loop stops
at 12, so the recorded ``distorted`` value is upstream's *unconverged* answer —
a behaviour this port has to reproduce rather than improve on.
``(200, 200)`` has a pre-image *outside* the frame (x lands at about -57 px):
the map compresses the frame's edge toward the centre, so a target near the
edge inverts to a point beyond it. Both would look like bugs to anyone reading
the numbers without knowing where they came from.

The reference is not bit-reproducible across builds (recompiling shifts values
by an ULP), and it computes in f32 while the port computes in f64, so the test
that consumes this fixture compares with a relative tolerance rather than for
equality.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

GOLDEN_DIR = Path(__file__).parent
FIXTURE = GOLDEN_DIR / "gopro6_superview.json"

# (name, width, height, probes in pixels). Every probe is (x, y).
CASES = [
    (
        "1080p_frame",
        1920,
        1080,
        [
            (960.0, 540.0),  # exact centre
            (1440.0, 540.0),  # +0.25 w
            (480.0, 540.0),  # -0.25 w
            (960.0, 810.0),  # +0.25 h
            (960.0, 270.0),  # -0.25 h
            (1728.0, 864.0),  # +0.4 w, +0.3 h
            (192.0, 216.0),  # -0.4 w, -0.3 h
            (200.0, 200.0),  # the pre-image of this one is outside the frame
            (1720.0, 880.0),  # the same region, positive y
            (100.0, 900.0),  # needs 22 fixed-point steps, upstream caps at 12
        ],
    ),
    (
        "4k_frame",
        3840,
        2160,
        [
            (1920.0, 1080.0),
            (2880.0, 1080.0),
            (960.0, 1080.0),
            (1920.0, 1620.0),
            (1920.0, 540.0),
            (3456.0, 1728.0),
            (384.0, 432.0),
        ],
    ),
    (
        "4_3_frame",
        1280,
        960,
        [
            (640.0, 480.0),
            (960.0, 480.0),
            (320.0, 480.0),
            (640.0, 720.0),
            (640.0, 240.0),
            (1152.0, 768.0),
        ],
    ),
]


def _skeleton() -> dict:
    return {
        "description": (
            "GoPro6 Superview digital lens reference: upstream "
            "gopro6_superview.rs run verbatim"
        ),
        "_provenance": (
            "Generated by tests/golden/generate_gopro6_superview_reference.py from "
            "the upstream Rust source, not from the Python port. The model is f32 "
            "upstream and f64 here, and the reference is not bit-reproducible "
            "across builds, so compare with a relative tolerance of 1e-6."
        ),
        "cases": [
            {"name": name, "width": w, "height": h, "probes": [list(p) for p in probes]}
            for name, w, h, probes in CASES
        ],
    }


def main() -> int:
    args = sys.argv[1:]
    check = "--check" in args
    rest = [a for a in args if a != "--check"]

    if not rest:
        print(__doc__)
        print(f"fixture:   {FIXTURE}")
        if FIXTURE.is_file():
            with open(FIXTURE, encoding="utf-8") as handle:
                cases = json.load(handle)["cases"]
            print(f"{len(cases)} case(s), {sum(len(c['probes']) for c in cases)} probe(s)")
        return 0

    binary = Path(rest[0]) / "target" / "release" / "gp6ref"
    if not binary.is_file():
        print(f"no reference binary at {binary}", file=sys.stderr)
        print("build it as described above", file=sys.stderr)
        return 2

    if not check:
        with open(FIXTURE, "w", encoding="utf-8") as handle:
            json.dump(_skeleton(), handle, indent=2)
            handle.write("\n")

    command = [str(binary), str(FIXTURE)]
    if check:
        command.append("--check")
    result = subprocess.run(command, capture_output=True, text=True)
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)
    return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
